Repository Wanted-Pre-Onboarding-Android-team3-2/android-wanted-MovieReviewApp, pull requests merged in 2022-10, with the labels that each got.

#8 [FIX] Binding
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/MovieApplication.kt
  presentation/src/main/AndroidManifest.xml
Labels: DONE, fix, 정호 :unicorn:

#9 [FEAT] 리뷰 관리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/di/RepositoryModule.kt
  app/src/main/res/layout/activity_main.xml
  data/src/main/java/com/preonboarding/data/repositoryimpl/FirebaseRepositoryImpl.kt
  domain/src/main/java/com/preonboarding/domain/model/EditState.kt
  domain/src/main/java/com/preonboarding/domain/model/Review.kt
  domain/src/main/java/com/preonboarding/domain/model/ReviewUiState.kt
  domain/src/main/java/com/preonboarding/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/preonboarding/domain/usecase/DeleteReviewUseCase.kt
  domain/src/main/java/com/preonboarding/domain/usecase/GetReviewListUseCase.kt
  domain/src/main/java/com/preonboarding/domain/usecase/UploadReviewUseCase.kt
  presentation/src/main/java/com/preonboarding/presentation/common/base/BaseDialogFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/common/shared/ViewExtenstions.kt
  presentation/src/main/java/com/preonboarding/presentation/common/utils/ThrottleClickListener.kt
  presentation/src/main/java/com/preonboarding/presentation/view/detail/DetailFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/view/detail/DetailViewModel.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewBindingAdapter.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewDialog.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewValidationDialog.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewViewModel.kt
  presentation/src/main/res/drawable/bg_dialog_button.xml
  presentation/src/main/res/drawable/bg_review_dialog.xml
  presentation/src/main/res/drawable/ic_back.xml
  presentation/src/main/res/drawable/ic_image_search.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/dialog_review.xml
  presentation/src/main/res/layout/dialog_review_validataion.xml
  presentation/src/main/res/layout/fragment_detail.xml
  presentation/src/main/res/layout/fragment_review.xml
  presentation/src/main/res/values/strings.xml
Labels: DONE, feature, 현수 :unicorn:

#12 [Feat]detail page
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  data/build.gradle.kts
  data/src/main/java/com/preonboarding/data/remote/response/boxoffice/DailyBoxOffice.kt
  data/src/main/java/com/preonboarding/data/repositoryimpl/FirebaseRepositoryImpl.kt
  data/src/main/java/com/preonboarding/data/repositoryimpl/MovieRepositoryImpl.kt
  domain/src/main/java/com/preonboarding/domain/model/Movie.kt
  domain/src/main/java/com/preonboarding/domain/repository/FirebaseRepository.kt
  domain/src/main/java/com/preonboarding/domain/usecase/UpdateReviewUseCase.kt
  google-services.json
  presentation/build.gradle.kts
  presentation/src/main/java/com/preonboarding/presentation/view/adapter/DetailReviewAdapter.kt
  presentation/src/main/java/com/preonboarding/presentation/view/detail/DetailFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/view/detail/DetailViewModel.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewDialog.kt
  presentation/src/main/res/drawable/button_border.xml
  presentation/src/main/res/drawable/detail_border.xml
  presentation/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
  presentation/src/main/res/drawable/ic_baseline_delete_forever_24.xml
  presentation/src/main/res/drawable/ic_baseline_edit_24.xml
  presentation/src/main/res/drawable/ic_baseline_more_vert_24.xml
  presentation/src/main/res/drawable/ic_baseline_movie_filter_24.xml
  presentation/src/main/res/drawable/ic_baseline_share_24.xml
  presentation/src/main/res/drawable/iv_border.xml
  presentation/src/main/res/drawable/no_img.png
  presentation/src/main/res/drawable/review_border.xml
  presentation/src/main/res/layout/dialog_review.xml
  presentation/src/main/res/layout/dialog_review_validataion.xml
  presentation/src/main/res/layout/fragment_detail.xml
  presentation/src/main/res/layout/fragment_list.xml
  presentation/src/main/res/layout/item_actors.xml
  presentation/src/main/res/layout/item_movie.xml
  presentation/src/main/res/layout/item_review.xml
  presentation/src/main/res/navigation/wanted_navigation.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, IN PROGRESS, TODO, 준성 :unicorn:, add

#13 [FEAT] 영화 리스트 표현
  app/build.gradle.kts
  app/src/main/java/com/preonboarding/di/NetworkModule.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/preonboarding/data/remote/api/PosterService.kt
  data/src/main/java/com/preonboarding/data/remote/datasource/MovieRemoteDataSource.kt
  data/src/main/java/com/preonboarding/data/remote/datasourceimpl/MovieRemoteDataSourceImpl.kt
  data/src/main/java/com/preonboarding/data/remote/response/boxoffice/BoxOfficeListResponse.kt
  data/src/main/java/com/preonboarding/data/remote/response/boxoffice/BoxOfficeResult.kt
  data/src/main/java/com/preonboarding/data/remote/response/boxoffice/DailyBoxOffice.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Actor.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Audit.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Company.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Director.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Genre.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/MovieInfo.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/MovieInfoResponse.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/MovieInfoResult.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Nation.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/ShowType.kt
  data/src/main/java/com/preonboarding/data/remote/response/movieinfo/Staff.kt
  data/src/main/java/com/preonboarding/data/remote/response/poster/PosterResponse.kt
  data/src/main/java/com/preonboarding/data/remote/response/poster/Rating.kt
  data/src/main/java/com/preonboarding/data/repositoryimpl/MovieRepositoryImpl.kt
  domain/src/main/java/com/preonboarding/domain/model/ExampleModel.kt
  domain/src/main/java/com/preonboarding/domain/model/Movie.kt
  domain/src/main/java/com/preonboarding/domain/repository/MovieRepository.kt
  presentation/src/main/java/com/preonboarding/presentation/view/list/ListFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/view/list/ListViewModel.kt
  presentation/src/main/res/layout/fragment_list.xml
Labels: feature, ui, 정호 :unicorn:

#14 [FIX] 두번째 화면 mms 수정
  presentation/build.gradle.kts
  presentation/src/main/java/com/preonboarding/presentation/view/detail/DetailFragment.kt
  presentation/src/main/java/com/preonboarding/presentation/view/review/ReviewDialog.kt
  presentation/src/main/res/layout/fragment_detail.xml
Labels: fix, ui, 준성 :unicorn:, add
